# Generated by Django 3.1.1 on 2021-05-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.AutoField(primary_key=True, serialize=False)),
                ('StudentFirstName', models.CharField(max_length=20)),
                ('StudentMiddleName', models.CharField(max_length=20)),
                ('StudentLastName', models.CharField(max_length=20)),
                ('BirthDate', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('std', models.IntegerField()),
                ('Enroll', models.IntegerField()),
                ('SchoolName', models.CharField(max_length=100)),
                ('Hobbies', models.CharField(max_length=200)),
                ('Refference', models.CharField(max_length=100)),
                ('Ressidence', models.TextField()),
                ('FatherName', models.CharField(max_length=70)),
                ('FatherQualification', models.CharField(max_length=200)),
                ('FatherOccupation', models.CharField(max_length=100)),
                ('FatherEmail', models.EmailField(max_length=254)),
                ('FatherContact1', models.IntegerField()),
                ('FatherContact2', models.IntegerField()),
                ('MotherName', models.CharField(max_length=70)),
                ('MotherQualification', models.CharField(max_length=100)),
                ('MotherOccupation', models.CharField(max_length=100)),
                ('MotherEmail', models.EmailField(max_length=254)),
                ('MotherContact1', models.IntegerField()),
                ('MotherContact2', models.IntegerField()),
            ],
        ),
    ]
