# Generated by Django 3.1.1 on 2021-05-19 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210518_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='StudentUserName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='BirthDate',
            field=models.DateField(blank=True, default=datetime.date(2000, 2, 26), null=True),
        ),
    ]
