# Generated by Django 3.1.1 on 2021-05-19 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20210519_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='regDate',
            new_name='date',
        ),
    ]
