# Generated by Django 3.1.1 on 2021-09-12 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20210519_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='date',
            new_name='JoiningDate',
        ),
    ]
