# Generated by Django 3.1.1 on 2021-09-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20210912_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='JoiningDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
