# Generated by Django 3.2.9 on 2021-11-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_student_joiningdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='JoiningDate',
            field=models.DateTimeField(null=True),
        ),
    ]
