# Generated by Django 3.1.1 on 2021-05-18 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentFirstName', models.CharField(default='', max_length=20)),
                ('StudentMiddleName', models.CharField(default='', max_length=20)),
                ('StudentLastName', models.CharField(default='', max_length=20)),
                ('BirthDate', models.CharField(default='', max_length=20)),
                ('Gender', models.CharField(default='', max_length=10)),
                ('StudentEmail', models.EmailField(default='', max_length=254)),
                ('std', models.IntegerField(default=0)),
                ('Enroll', models.IntegerField(default=0)),
                ('SchoolName', models.CharField(default='', max_length=100)),
                ('Hobbies', models.CharField(default='', max_length=200)),
                ('Refference', models.CharField(default='', max_length=100)),
                ('Ressidence', models.TextField(default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
