# Generated by Django 3.1.1 on 2021-05-19 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='BirthDate',
            field=models.DateField(blank=True, default=datetime.date(2000, 2, 26), null=True),
        ),
    ]
