# Generated by Django 3.1.1 on 2021-05-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210519_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='BirthDate',
            field=models.CharField(default='', max_length=50),
        ),
    ]
