# Generated by Django 3.1.1 on 2021-05-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210519_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
