# Generated by Django 3.1.1 on 2021-05-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='StudentUserName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='ucmaslevel',
            field=models.IntegerField(default=1),
        ),
    ]
