# Generated by Django 3.1.1 on 2021-05-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210519_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='StudentFirstName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='StudentLastName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='StudentMiddleName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='StudentUserName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
